### ISSUE TITLE
Elements with display: none should not affect the layout of other elements

### ISSUE THREAD

**Issue by soundasleep** [radkovo/CSSBox#73]
Given the following HTML:

```html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="base.css">
</head>
<body>
  <label type="toggle-button">
    <input type="radio" name="elementx">
    Hello
  </label>
</body>
</html>
```

And the following CSS:

```css
label[type="toggle-button"] {
  border: 1px solid white;
  color: white;
  display: inline-block;
  margin: 0;
  padding: 16px;
}

label[type="toggle-button"] > input[type="radio"] {
    display: none;
}
```

The `<input>` _should not_ be displayed (and thus not affecting the layout of the parent `<label>`), but it seems to be affecting layout:

![image](https://user-images.githubusercontent.com/3889656/158921518-a514cba1-f033-4ff4-a10f-2bdb5a7a5d17.png)

In fact you can change the properties of the `display: none;` input, for example:

```css
label[type="toggle-button"] > input[type="radio"] {
    display: none;
    padding: 64px;
    margin: 64px;
}
```

This renders as:

![image](https://user-images.githubusercontent.com/3889656/158921571-66714c49-cbc1-4e81-bb9b-e0a51555949d.png)

(This might be an issue in [jStyleParser](https://github.com/radkovo/jStyleParser), not sure)
